- hosts: vms
  become: yes
  tasks:

    - name: Gather facts on listening ports
      community.general.listen_ports_facts:

    - name: TCP whitelist violation
      ansible.builtin.debug:
        msg: TCP port {{ item.port }} by pid {{ item.pid }} violates the whitelist
      vars:
        tcp_listen_violations: "{{ ansible_facts.tcp_listen | selectattr('port', 'in', tcp_whitelist) | list }}"
        tcp_whitelist:
          - 22
          - 25
          - 80
          - 111
      loop: "{{ tcp_listen_violations }}"

    - name: List TCP ports
      ansible.builtin.debug:
        msg: "{{ ansible_facts.tcp_listen  | map(attribute='port') | sort | list }}"

    - name: List UDP ports
      ansible.builtin.debug:
        msg: "{{ ansible_facts.udp_listen | map(attribute='port') | sort | list }}"

    - name: List all ports
      ansible.builtin.debug:
        msg: "{{ (ansible_facts.tcp_listen + ansible_facts.udp_listen) | map(attribute='port') | unique | sort | list }}"
